### ISSUE TITLE
Log-in Mockup

### ISSUE THREAD

**Issue by jerkodeur** [jerkodeur/shareMyEvents#102]
Related to #1 

# Tasks

### Angular
- [x] Import form module
- [x] Create component

### Controller
- [x] Create interface
- [x] Create class
- [x] Create formBuilder binding
- [x] Create validations
- [x] Verify if the data is received from the form

### HTML
- [x] Create the HTML form
- [x] Handle errors
- [x] Display errors in form in case of invalid user entries

### Acceptance criteria
- [x] The errors are handled
- [x] The user cannot validate the form if this is invalid
- [x] Required fields are mentioned
- [x] Errors are displayed on the forms when occurred
- [x] The page is responsive
- [x] The nav icon switch to yellow when on the page
- [x] The mockup suit with the wireframe
- [x] HTML Tags used are suitable for accessibility
