### ISSUE TITLE
As an organizer, I can edit the event  guest list

### ISSUE THREAD

**Issue by jerkodeur** [jerkodeur/shareMyEvents#16]
### I want to be informed of:

- The guest list

### I want to be able to :

- Add a new guest
  - #17 
- Remove a guest from the list
  - #19

**Comment by jerkodeur** [comment]
## For editing the event guest list

### I want to be informed of:

- [ ] The guest list

### I want to be able to :

- [ ] Add a new guest
- [ ] Modify a guest information 
- [ ] Remove a guest from the list

**Comment by jerkodeur** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gérer les invitations](https://trello.com/c/0733P2e7/3-g%C3%A9rer-les-invitations)
