### ISSUE TITLE
Support de présentation

### ISSUE THREAD

**Issue by jerkodeur** [jerkodeur/shareMyEvents#73]
- [x] Slide garde
  - [x] Nom du projet
  - [x] Identité
  - [x] Titre visé 
  - [x] (Date de la soutenance)
  - [x] (Ecole / programme)
- [x] Sommaire (pas trop chargé, Introduction, Besoins, Conception, Conclusion, Q/R)
- [x] Résumé du projet (Phrases d'accroches, l'essentiel) `Quelques lignes`
- [x] Expression des besoins (Liste allégée des principales fonctionnalités) `Bullet point` `1 Slide`
- [x] Persona `1 slide` `1 / 2 persona` #71 
- [x] Gestion de projet (mise en place des outils de gestion, agilité, GitHub) `max 3 slides`
  - [x] Vues du kanban des US
  - [x] Vue du kanban des tâches 
  - [x] Zoom sur 1 user Story #1 
- [x] Cas d'utilisation  (1 diagramme, création de compte, authentification) #74 
- [x] Zoning `1 ou 2 slide` `desktop et mobile`
- [x] Wireframe 1 (Création de compte desktop) 
- [x] Wireframe 2 (Authentification responsive)
- [x] Charte graphique #57 
- [x] Site map (1 ou 2 slide) #58 
- [x] Résolution d'un problème sur un site Anglophone` #72 
- [x] Conclusion
  - [x] Difficultés rencontrées
  - [x] Satisfactions
  - [x] Ce que j'ai appris
  - [x] Prochaines étapes
  - [x] Mot de la fin
